url: https://y7kim.github.io
baseurl: /clinica-pies/

# Site settings
title: ClinicaPies
email: clinicapies.brunete@gmail.com
description: "Clínica de podología"


# Team names, titles and social links
people:
- name: María Gallego Pizarro
  pic: 1
  position: Podóloga jefa
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Calle Real de San Sebastián, 23
  - line: Brunete, Madrid (28690)

# Build settings
markdown: kramdown
permalink: pretty